[package]
edition = "2021"
name = "grrs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.0", features = ["derive"]}
env_logger = "0.9.0"
log = "0.4.17"
